version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
      - npm install
  build:
    commands:
      - echo "Build phase"
      - npm start
artifacts:
  files:
    - '**/*'
  base-directory: 'build' 
 