version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building reactjs project..."
      - npm run build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 cp build/github-s3-react-app/ s3://giloihoaizma --recursive